// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.2
// source: route/v1/route.proto

package routev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RouteService_CreateNode_FullMethodName     = "/route.v1.RouteService/CreateNode"
	RouteService_UpdateNode_FullMethodName     = "/route.v1.RouteService/UpdateNode"
	RouteService_GetNode_FullMethodName        = "/route.v1.RouteService/GetNode"
	RouteService_DeleteNode_FullMethodName     = "/route.v1.RouteService/DeleteNode"
	RouteService_ListNodes_FullMethodName      = "/route.v1.RouteService/ListNodes"
	RouteService_CreateEdge_FullMethodName     = "/route.v1.RouteService/CreateEdge"
	RouteService_UpdateEdge_FullMethodName     = "/route.v1.RouteService/UpdateEdge"
	RouteService_GetEdge_FullMethodName        = "/route.v1.RouteService/GetEdge"
	RouteService_DeleteEdge_FullMethodName     = "/route.v1.RouteService/DeleteEdge"
	RouteService_ListEdges_FullMethodName      = "/route.v1.RouteService/ListEdges"
	RouteService_CalculateRoute_FullMethodName = "/route.v1.RouteService/CalculateRoute"
	RouteService_GetDistance_FullMethodName    = "/route.v1.RouteService/GetDistance"
	RouteService_BatchCalculate_FullMethodName = "/route.v1.RouteService/BatchCalculate"
)

// RouteServiceClient is the client API for RouteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RouteServiceClient interface {
	// Node CRUD
	CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error)
	UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error)
	DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error)
	ListNodes(ctx context.Context, in *ListNodeRequest, opts ...grpc.CallOption) (*NodeListResponse, error)
	// Edge CRUD
	CreateEdge(ctx context.Context, in *CreateEdgeRequest, opts ...grpc.CallOption) (*EdgeResponse, error)
	UpdateEdge(ctx context.Context, in *UpdateEdgeRequest, opts ...grpc.CallOption) (*EdgeResponse, error)
	GetEdge(ctx context.Context, in *GetEdgeRequest, opts ...grpc.CallOption) (*EdgeResponse, error)
	DeleteEdge(ctx context.Context, in *DeleteEdgeRequest, opts ...grpc.CallOption) (*EdgeResponse, error)
	ListEdges(ctx context.Context, in *ListEdgeRequest, opts ...grpc.CallOption) (*EdgeListResponse, error)
	// Routing
	CalculateRoute(ctx context.Context, in *CalculateRouteRequest, opts ...grpc.CallOption) (*RouteResponse, error)
	GetDistance(ctx context.Context, in *GetDistanceRequest, opts ...grpc.CallOption) (*DistanceResponse, error)
	BatchCalculate(ctx context.Context, in *BatchRouteRequest, opts ...grpc.CallOption) (*BatchRouteResponse, error)
}

type routeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRouteServiceClient(cc grpc.ClientConnInterface) RouteServiceClient {
	return &routeServiceClient{cc}
}

func (c *routeServiceClient) CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, RouteService_CreateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, RouteService_UpdateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, RouteService_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, RouteService_DeleteNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) ListNodes(ctx context.Context, in *ListNodeRequest, opts ...grpc.CallOption) (*NodeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeListResponse)
	err := c.cc.Invoke(ctx, RouteService_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) CreateEdge(ctx context.Context, in *CreateEdgeRequest, opts ...grpc.CallOption) (*EdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EdgeResponse)
	err := c.cc.Invoke(ctx, RouteService_CreateEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) UpdateEdge(ctx context.Context, in *UpdateEdgeRequest, opts ...grpc.CallOption) (*EdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EdgeResponse)
	err := c.cc.Invoke(ctx, RouteService_UpdateEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) GetEdge(ctx context.Context, in *GetEdgeRequest, opts ...grpc.CallOption) (*EdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EdgeResponse)
	err := c.cc.Invoke(ctx, RouteService_GetEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) DeleteEdge(ctx context.Context, in *DeleteEdgeRequest, opts ...grpc.CallOption) (*EdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EdgeResponse)
	err := c.cc.Invoke(ctx, RouteService_DeleteEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) ListEdges(ctx context.Context, in *ListEdgeRequest, opts ...grpc.CallOption) (*EdgeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EdgeListResponse)
	err := c.cc.Invoke(ctx, RouteService_ListEdges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) CalculateRoute(ctx context.Context, in *CalculateRouteRequest, opts ...grpc.CallOption) (*RouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteResponse)
	err := c.cc.Invoke(ctx, RouteService_CalculateRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) GetDistance(ctx context.Context, in *GetDistanceRequest, opts ...grpc.CallOption) (*DistanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DistanceResponse)
	err := c.cc.Invoke(ctx, RouteService_GetDistance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) BatchCalculate(ctx context.Context, in *BatchRouteRequest, opts ...grpc.CallOption) (*BatchRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchRouteResponse)
	err := c.cc.Invoke(ctx, RouteService_BatchCalculate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouteServiceServer is the server API for RouteService service.
// All implementations must embed UnimplementedRouteServiceServer
// for forward compatibility.
type RouteServiceServer interface {
	// Node CRUD
	CreateNode(context.Context, *CreateNodeRequest) (*NodeResponse, error)
	UpdateNode(context.Context, *UpdateNodeRequest) (*NodeResponse, error)
	GetNode(context.Context, *GetNodeRequest) (*NodeResponse, error)
	DeleteNode(context.Context, *DeleteNodeRequest) (*NodeResponse, error)
	ListNodes(context.Context, *ListNodeRequest) (*NodeListResponse, error)
	// Edge CRUD
	CreateEdge(context.Context, *CreateEdgeRequest) (*EdgeResponse, error)
	UpdateEdge(context.Context, *UpdateEdgeRequest) (*EdgeResponse, error)
	GetEdge(context.Context, *GetEdgeRequest) (*EdgeResponse, error)
	DeleteEdge(context.Context, *DeleteEdgeRequest) (*EdgeResponse, error)
	ListEdges(context.Context, *ListEdgeRequest) (*EdgeListResponse, error)
	// Routing
	CalculateRoute(context.Context, *CalculateRouteRequest) (*RouteResponse, error)
	GetDistance(context.Context, *GetDistanceRequest) (*DistanceResponse, error)
	BatchCalculate(context.Context, *BatchRouteRequest) (*BatchRouteResponse, error)
	mustEmbedUnimplementedRouteServiceServer()
}

// UnimplementedRouteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRouteServiceServer struct{}

func (UnimplementedRouteServiceServer) CreateNode(context.Context, *CreateNodeRequest) (*NodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNode not implemented")
}
func (UnimplementedRouteServiceServer) UpdateNode(context.Context, *UpdateNodeRequest) (*NodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNode not implemented")
}
func (UnimplementedRouteServiceServer) GetNode(context.Context, *GetNodeRequest) (*NodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedRouteServiceServer) DeleteNode(context.Context, *DeleteNodeRequest) (*NodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNode not implemented")
}
func (UnimplementedRouteServiceServer) ListNodes(context.Context, *ListNodeRequest) (*NodeListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedRouteServiceServer) CreateEdge(context.Context, *CreateEdgeRequest) (*EdgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEdge not implemented")
}
func (UnimplementedRouteServiceServer) UpdateEdge(context.Context, *UpdateEdgeRequest) (*EdgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEdge not implemented")
}
func (UnimplementedRouteServiceServer) GetEdge(context.Context, *GetEdgeRequest) (*EdgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEdge not implemented")
}
func (UnimplementedRouteServiceServer) DeleteEdge(context.Context, *DeleteEdgeRequest) (*EdgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEdge not implemented")
}
func (UnimplementedRouteServiceServer) ListEdges(context.Context, *ListEdgeRequest) (*EdgeListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEdges not implemented")
}
func (UnimplementedRouteServiceServer) CalculateRoute(context.Context, *CalculateRouteRequest) (*RouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateRoute not implemented")
}
func (UnimplementedRouteServiceServer) GetDistance(context.Context, *GetDistanceRequest) (*DistanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDistance not implemented")
}
func (UnimplementedRouteServiceServer) BatchCalculate(context.Context, *BatchRouteRequest) (*BatchRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchCalculate not implemented")
}
func (UnimplementedRouteServiceServer) mustEmbedUnimplementedRouteServiceServer() {}
func (UnimplementedRouteServiceServer) testEmbeddedByValue()                      {}

// UnsafeRouteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouteServiceServer will
// result in compilation errors.
type UnsafeRouteServiceServer interface {
	mustEmbedUnimplementedRouteServiceServer()
}

func RegisterRouteServiceServer(s grpc.ServiceRegistrar, srv RouteServiceServer) {
	// If the following call pancis, it indicates UnimplementedRouteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RouteService_ServiceDesc, srv)
}

func _RouteService_CreateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).CreateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteService_CreateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).CreateNode(ctx, req.(*CreateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_UpdateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).UpdateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteService_UpdateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).UpdateNode(ctx, req.(*UpdateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteService_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_DeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).DeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteService_DeleteNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).DeleteNode(ctx, req.(*DeleteNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteService_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).ListNodes(ctx, req.(*ListNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_CreateEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).CreateEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteService_CreateEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).CreateEdge(ctx, req.(*CreateEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_UpdateEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).UpdateEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteService_UpdateEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).UpdateEdge(ctx, req.(*UpdateEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_GetEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).GetEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteService_GetEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).GetEdge(ctx, req.(*GetEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_DeleteEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).DeleteEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteService_DeleteEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).DeleteEdge(ctx, req.(*DeleteEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_ListEdges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).ListEdges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteService_ListEdges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).ListEdges(ctx, req.(*ListEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_CalculateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).CalculateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteService_CalculateRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).CalculateRoute(ctx, req.(*CalculateRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_GetDistance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDistanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).GetDistance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteService_GetDistance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).GetDistance(ctx, req.(*GetDistanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_BatchCalculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).BatchCalculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteService_BatchCalculate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).BatchCalculate(ctx, req.(*BatchRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RouteService_ServiceDesc is the grpc.ServiceDesc for RouteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RouteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "route.v1.RouteService",
	HandlerType: (*RouteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNode",
			Handler:    _RouteService_CreateNode_Handler,
		},
		{
			MethodName: "UpdateNode",
			Handler:    _RouteService_UpdateNode_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _RouteService_GetNode_Handler,
		},
		{
			MethodName: "DeleteNode",
			Handler:    _RouteService_DeleteNode_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _RouteService_ListNodes_Handler,
		},
		{
			MethodName: "CreateEdge",
			Handler:    _RouteService_CreateEdge_Handler,
		},
		{
			MethodName: "UpdateEdge",
			Handler:    _RouteService_UpdateEdge_Handler,
		},
		{
			MethodName: "GetEdge",
			Handler:    _RouteService_GetEdge_Handler,
		},
		{
			MethodName: "DeleteEdge",
			Handler:    _RouteService_DeleteEdge_Handler,
		},
		{
			MethodName: "ListEdges",
			Handler:    _RouteService_ListEdges_Handler,
		},
		{
			MethodName: "CalculateRoute",
			Handler:    _RouteService_CalculateRoute_Handler,
		},
		{
			MethodName: "GetDistance",
			Handler:    _RouteService_GetDistance_Handler,
		},
		{
			MethodName: "BatchCalculate",
			Handler:    _RouteService_BatchCalculate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "route/v1/route.proto",
}
