global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'go-zero-services'
    static_configs:
      - targets:
        - 'gateway:6060'
        - 'user-service:6060'
        - 'auth-service:6060'
        - 'vehicle-service:6060'
        - 'telemetry-service:6060'
        - 'dispatch-service:6060'
        - 'ai-service:6060'
        - 'alarm-service:6060'
        - 'route-service:6060'
        - 'device-service:6060'
