// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.2
// source: alarm/v1/alarm.proto

package alarmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AlarmService_CreateGeofence_FullMethodName   = "/alarm.v1.AlarmService/CreateGeofence"
	AlarmService_UpdateGeofence_FullMethodName   = "/alarm.v1.AlarmService/UpdateGeofence"
	AlarmService_GetGeofence_FullMethodName      = "/alarm.v1.AlarmService/GetGeofence"
	AlarmService_DeleteGeofence_FullMethodName   = "/alarm.v1.AlarmService/DeleteGeofence"
	AlarmService_ListGeofences_FullMethodName    = "/alarm.v1.AlarmService/ListGeofences"
	AlarmService_CreateAlarmRule_FullMethodName  = "/alarm.v1.AlarmService/CreateAlarmRule"
	AlarmService_UpdateAlarmRule_FullMethodName  = "/alarm.v1.AlarmService/UpdateAlarmRule"
	AlarmService_GetAlarmRule_FullMethodName     = "/alarm.v1.AlarmService/GetAlarmRule"
	AlarmService_DeleteAlarmRule_FullMethodName  = "/alarm.v1.AlarmService/DeleteAlarmRule"
	AlarmService_ListAlarmRules_FullMethodName   = "/alarm.v1.AlarmService/ListAlarmRules"
	AlarmService_ListAlarmEvents_FullMethodName  = "/alarm.v1.AlarmService/ListAlarmEvents"
	AlarmService_AcknowledgeAlarm_FullMethodName = "/alarm.v1.AlarmService/AcknowledgeAlarm"
	AlarmService_CheckPosition_FullMethodName    = "/alarm.v1.AlarmService/CheckPosition"
)

// AlarmServiceClient is the client API for AlarmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlarmServiceClient interface {
	// Geofence
	CreateGeofence(ctx context.Context, in *CreateGeofenceRequest, opts ...grpc.CallOption) (*GeofenceResponse, error)
	UpdateGeofence(ctx context.Context, in *UpdateGeofenceRequest, opts ...grpc.CallOption) (*GeofenceResponse, error)
	GetGeofence(ctx context.Context, in *GetGeofenceRequest, opts ...grpc.CallOption) (*GeofenceResponse, error)
	DeleteGeofence(ctx context.Context, in *DeleteGeofenceRequest, opts ...grpc.CallOption) (*GeofenceResponse, error)
	ListGeofences(ctx context.Context, in *ListGeofencesRequest, opts ...grpc.CallOption) (*GeofenceListResponse, error)
	// Alarm Rules
	CreateAlarmRule(ctx context.Context, in *CreateAlarmRuleRequest, opts ...grpc.CallOption) (*AlarmRuleResponse, error)
	UpdateAlarmRule(ctx context.Context, in *UpdateAlarmRuleRequest, opts ...grpc.CallOption) (*AlarmRuleResponse, error)
	GetAlarmRule(ctx context.Context, in *GetAlarmRuleRequest, opts ...grpc.CallOption) (*AlarmRuleResponse, error)
	DeleteAlarmRule(ctx context.Context, in *DeleteAlarmRuleRequest, opts ...grpc.CallOption) (*AlarmRuleResponse, error)
	ListAlarmRules(ctx context.Context, in *ListAlarmRulesRequest, opts ...grpc.CallOption) (*AlarmRuleListResponse, error)
	// Alarm Events
	ListAlarmEvents(ctx context.Context, in *ListAlarmEventsRequest, opts ...grpc.CallOption) (*AlarmEventListResponse, error)
	AcknowledgeAlarm(ctx context.Context, in *AcknowledgeAlarmRequest, opts ...grpc.CallOption) (*AlarmEventResponse, error)
	// Position check (called by telemetry service)
	CheckPosition(ctx context.Context, in *CheckPositionRequest, opts ...grpc.CallOption) (*CheckPositionResponse, error)
}

type alarmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlarmServiceClient(cc grpc.ClientConnInterface) AlarmServiceClient {
	return &alarmServiceClient{cc}
}

func (c *alarmServiceClient) CreateGeofence(ctx context.Context, in *CreateGeofenceRequest, opts ...grpc.CallOption) (*GeofenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeofenceResponse)
	err := c.cc.Invoke(ctx, AlarmService_CreateGeofence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmServiceClient) UpdateGeofence(ctx context.Context, in *UpdateGeofenceRequest, opts ...grpc.CallOption) (*GeofenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeofenceResponse)
	err := c.cc.Invoke(ctx, AlarmService_UpdateGeofence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmServiceClient) GetGeofence(ctx context.Context, in *GetGeofenceRequest, opts ...grpc.CallOption) (*GeofenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeofenceResponse)
	err := c.cc.Invoke(ctx, AlarmService_GetGeofence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmServiceClient) DeleteGeofence(ctx context.Context, in *DeleteGeofenceRequest, opts ...grpc.CallOption) (*GeofenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeofenceResponse)
	err := c.cc.Invoke(ctx, AlarmService_DeleteGeofence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmServiceClient) ListGeofences(ctx context.Context, in *ListGeofencesRequest, opts ...grpc.CallOption) (*GeofenceListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeofenceListResponse)
	err := c.cc.Invoke(ctx, AlarmService_ListGeofences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmServiceClient) CreateAlarmRule(ctx context.Context, in *CreateAlarmRuleRequest, opts ...grpc.CallOption) (*AlarmRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlarmRuleResponse)
	err := c.cc.Invoke(ctx, AlarmService_CreateAlarmRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmServiceClient) UpdateAlarmRule(ctx context.Context, in *UpdateAlarmRuleRequest, opts ...grpc.CallOption) (*AlarmRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlarmRuleResponse)
	err := c.cc.Invoke(ctx, AlarmService_UpdateAlarmRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmServiceClient) GetAlarmRule(ctx context.Context, in *GetAlarmRuleRequest, opts ...grpc.CallOption) (*AlarmRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlarmRuleResponse)
	err := c.cc.Invoke(ctx, AlarmService_GetAlarmRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmServiceClient) DeleteAlarmRule(ctx context.Context, in *DeleteAlarmRuleRequest, opts ...grpc.CallOption) (*AlarmRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlarmRuleResponse)
	err := c.cc.Invoke(ctx, AlarmService_DeleteAlarmRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmServiceClient) ListAlarmRules(ctx context.Context, in *ListAlarmRulesRequest, opts ...grpc.CallOption) (*AlarmRuleListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlarmRuleListResponse)
	err := c.cc.Invoke(ctx, AlarmService_ListAlarmRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmServiceClient) ListAlarmEvents(ctx context.Context, in *ListAlarmEventsRequest, opts ...grpc.CallOption) (*AlarmEventListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlarmEventListResponse)
	err := c.cc.Invoke(ctx, AlarmService_ListAlarmEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmServiceClient) AcknowledgeAlarm(ctx context.Context, in *AcknowledgeAlarmRequest, opts ...grpc.CallOption) (*AlarmEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlarmEventResponse)
	err := c.cc.Invoke(ctx, AlarmService_AcknowledgeAlarm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmServiceClient) CheckPosition(ctx context.Context, in *CheckPositionRequest, opts ...grpc.CallOption) (*CheckPositionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPositionResponse)
	err := c.cc.Invoke(ctx, AlarmService_CheckPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlarmServiceServer is the server API for AlarmService service.
// All implementations must embed UnimplementedAlarmServiceServer
// for forward compatibility.
type AlarmServiceServer interface {
	// Geofence
	CreateGeofence(context.Context, *CreateGeofenceRequest) (*GeofenceResponse, error)
	UpdateGeofence(context.Context, *UpdateGeofenceRequest) (*GeofenceResponse, error)
	GetGeofence(context.Context, *GetGeofenceRequest) (*GeofenceResponse, error)
	DeleteGeofence(context.Context, *DeleteGeofenceRequest) (*GeofenceResponse, error)
	ListGeofences(context.Context, *ListGeofencesRequest) (*GeofenceListResponse, error)
	// Alarm Rules
	CreateAlarmRule(context.Context, *CreateAlarmRuleRequest) (*AlarmRuleResponse, error)
	UpdateAlarmRule(context.Context, *UpdateAlarmRuleRequest) (*AlarmRuleResponse, error)
	GetAlarmRule(context.Context, *GetAlarmRuleRequest) (*AlarmRuleResponse, error)
	DeleteAlarmRule(context.Context, *DeleteAlarmRuleRequest) (*AlarmRuleResponse, error)
	ListAlarmRules(context.Context, *ListAlarmRulesRequest) (*AlarmRuleListResponse, error)
	// Alarm Events
	ListAlarmEvents(context.Context, *ListAlarmEventsRequest) (*AlarmEventListResponse, error)
	AcknowledgeAlarm(context.Context, *AcknowledgeAlarmRequest) (*AlarmEventResponse, error)
	// Position check (called by telemetry service)
	CheckPosition(context.Context, *CheckPositionRequest) (*CheckPositionResponse, error)
	mustEmbedUnimplementedAlarmServiceServer()
}

// UnimplementedAlarmServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlarmServiceServer struct{}

func (UnimplementedAlarmServiceServer) CreateGeofence(context.Context, *CreateGeofenceRequest) (*GeofenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGeofence not implemented")
}
func (UnimplementedAlarmServiceServer) UpdateGeofence(context.Context, *UpdateGeofenceRequest) (*GeofenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGeofence not implemented")
}
func (UnimplementedAlarmServiceServer) GetGeofence(context.Context, *GetGeofenceRequest) (*GeofenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGeofence not implemented")
}
func (UnimplementedAlarmServiceServer) DeleteGeofence(context.Context, *DeleteGeofenceRequest) (*GeofenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGeofence not implemented")
}
func (UnimplementedAlarmServiceServer) ListGeofences(context.Context, *ListGeofencesRequest) (*GeofenceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGeofences not implemented")
}
func (UnimplementedAlarmServiceServer) CreateAlarmRule(context.Context, *CreateAlarmRuleRequest) (*AlarmRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAlarmRule not implemented")
}
func (UnimplementedAlarmServiceServer) UpdateAlarmRule(context.Context, *UpdateAlarmRuleRequest) (*AlarmRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAlarmRule not implemented")
}
func (UnimplementedAlarmServiceServer) GetAlarmRule(context.Context, *GetAlarmRuleRequest) (*AlarmRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlarmRule not implemented")
}
func (UnimplementedAlarmServiceServer) DeleteAlarmRule(context.Context, *DeleteAlarmRuleRequest) (*AlarmRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAlarmRule not implemented")
}
func (UnimplementedAlarmServiceServer) ListAlarmRules(context.Context, *ListAlarmRulesRequest) (*AlarmRuleListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAlarmRules not implemented")
}
func (UnimplementedAlarmServiceServer) ListAlarmEvents(context.Context, *ListAlarmEventsRequest) (*AlarmEventListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAlarmEvents not implemented")
}
func (UnimplementedAlarmServiceServer) AcknowledgeAlarm(context.Context, *AcknowledgeAlarmRequest) (*AlarmEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcknowledgeAlarm not implemented")
}
func (UnimplementedAlarmServiceServer) CheckPosition(context.Context, *CheckPositionRequest) (*CheckPositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPosition not implemented")
}
func (UnimplementedAlarmServiceServer) mustEmbedUnimplementedAlarmServiceServer() {}
func (UnimplementedAlarmServiceServer) testEmbeddedByValue()                      {}

// UnsafeAlarmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlarmServiceServer will
// result in compilation errors.
type UnsafeAlarmServiceServer interface {
	mustEmbedUnimplementedAlarmServiceServer()
}

func RegisterAlarmServiceServer(s grpc.ServiceRegistrar, srv AlarmServiceServer) {
	// If the following call pancis, it indicates UnimplementedAlarmServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AlarmService_ServiceDesc, srv)
}

func _AlarmService_CreateGeofence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGeofenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).CreateGeofence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlarmService_CreateGeofence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).CreateGeofence(ctx, req.(*CreateGeofenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlarmService_UpdateGeofence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGeofenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).UpdateGeofence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlarmService_UpdateGeofence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).UpdateGeofence(ctx, req.(*UpdateGeofenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlarmService_GetGeofence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGeofenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).GetGeofence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlarmService_GetGeofence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).GetGeofence(ctx, req.(*GetGeofenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlarmService_DeleteGeofence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGeofenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).DeleteGeofence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlarmService_DeleteGeofence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).DeleteGeofence(ctx, req.(*DeleteGeofenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlarmService_ListGeofences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGeofencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).ListGeofences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlarmService_ListGeofences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).ListGeofences(ctx, req.(*ListGeofencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlarmService_CreateAlarmRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlarmRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).CreateAlarmRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlarmService_CreateAlarmRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).CreateAlarmRule(ctx, req.(*CreateAlarmRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlarmService_UpdateAlarmRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAlarmRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).UpdateAlarmRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlarmService_UpdateAlarmRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).UpdateAlarmRule(ctx, req.(*UpdateAlarmRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlarmService_GetAlarmRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlarmRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).GetAlarmRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlarmService_GetAlarmRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).GetAlarmRule(ctx, req.(*GetAlarmRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlarmService_DeleteAlarmRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAlarmRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).DeleteAlarmRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlarmService_DeleteAlarmRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).DeleteAlarmRule(ctx, req.(*DeleteAlarmRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlarmService_ListAlarmRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlarmRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).ListAlarmRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlarmService_ListAlarmRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).ListAlarmRules(ctx, req.(*ListAlarmRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlarmService_ListAlarmEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlarmEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).ListAlarmEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlarmService_ListAlarmEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).ListAlarmEvents(ctx, req.(*ListAlarmEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlarmService_AcknowledgeAlarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeAlarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).AcknowledgeAlarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlarmService_AcknowledgeAlarm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).AcknowledgeAlarm(ctx, req.(*AcknowledgeAlarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlarmService_CheckPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).CheckPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlarmService_CheckPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).CheckPosition(ctx, req.(*CheckPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlarmService_ServiceDesc is the grpc.ServiceDesc for AlarmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlarmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alarm.v1.AlarmService",
	HandlerType: (*AlarmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGeofence",
			Handler:    _AlarmService_CreateGeofence_Handler,
		},
		{
			MethodName: "UpdateGeofence",
			Handler:    _AlarmService_UpdateGeofence_Handler,
		},
		{
			MethodName: "GetGeofence",
			Handler:    _AlarmService_GetGeofence_Handler,
		},
		{
			MethodName: "DeleteGeofence",
			Handler:    _AlarmService_DeleteGeofence_Handler,
		},
		{
			MethodName: "ListGeofences",
			Handler:    _AlarmService_ListGeofences_Handler,
		},
		{
			MethodName: "CreateAlarmRule",
			Handler:    _AlarmService_CreateAlarmRule_Handler,
		},
		{
			MethodName: "UpdateAlarmRule",
			Handler:    _AlarmService_UpdateAlarmRule_Handler,
		},
		{
			MethodName: "GetAlarmRule",
			Handler:    _AlarmService_GetAlarmRule_Handler,
		},
		{
			MethodName: "DeleteAlarmRule",
			Handler:    _AlarmService_DeleteAlarmRule_Handler,
		},
		{
			MethodName: "ListAlarmRules",
			Handler:    _AlarmService_ListAlarmRules_Handler,
		},
		{
			MethodName: "ListAlarmEvents",
			Handler:    _AlarmService_ListAlarmEvents_Handler,
		},
		{
			MethodName: "AcknowledgeAlarm",
			Handler:    _AlarmService_AcknowledgeAlarm_Handler,
		},
		{
			MethodName: "CheckPosition",
			Handler:    _AlarmService_CheckPosition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alarm/v1/alarm.proto",
}
