// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.2
// source: proto/ai/v1/ai.proto

package aiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AiService_PredictCongestion_FullMethodName = "/ai.v1.AiService/PredictCongestion"
	AiService_RecommendRoute_FullMethodName    = "/ai.v1.AiService/RecommendRoute"
	AiService_PredictDemand_FullMethodName     = "/ai.v1.AiService/PredictDemand"
	AiService_SuggestAssign_FullMethodName     = "/ai.v1.AiService/SuggestAssign"
	AiService_HealthCheck_FullMethodName       = "/ai.v1.AiService/HealthCheck"
)

// AiServiceClient is the client API for AiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AiServiceClient interface {
	PredictCongestion(ctx context.Context, in *PredictCongestionRequest, opts ...grpc.CallOption) (*PredictCongestionResponse, error)
	RecommendRoute(ctx context.Context, in *RecommendRouteRequest, opts ...grpc.CallOption) (*RecommendRouteResponse, error)
	PredictDemand(ctx context.Context, in *PredictDemandRequest, opts ...grpc.CallOption) (*PredictDemandResponse, error)
	SuggestAssign(ctx context.Context, in *SuggestAssignRequest, opts ...grpc.CallOption) (*SuggestAssignResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type aiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAiServiceClient(cc grpc.ClientConnInterface) AiServiceClient {
	return &aiServiceClient{cc}
}

func (c *aiServiceClient) PredictCongestion(ctx context.Context, in *PredictCongestionRequest, opts ...grpc.CallOption) (*PredictCongestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictCongestionResponse)
	err := c.cc.Invoke(ctx, AiService_PredictCongestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) RecommendRoute(ctx context.Context, in *RecommendRouteRequest, opts ...grpc.CallOption) (*RecommendRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendRouteResponse)
	err := c.cc.Invoke(ctx, AiService_RecommendRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) PredictDemand(ctx context.Context, in *PredictDemandRequest, opts ...grpc.CallOption) (*PredictDemandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictDemandResponse)
	err := c.cc.Invoke(ctx, AiService_PredictDemand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) SuggestAssign(ctx context.Context, in *SuggestAssignRequest, opts ...grpc.CallOption) (*SuggestAssignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuggestAssignResponse)
	err := c.cc.Invoke(ctx, AiService_SuggestAssign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, AiService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiServiceServer is the server API for AiService service.
// All implementations must embed UnimplementedAiServiceServer
// for forward compatibility.
type AiServiceServer interface {
	PredictCongestion(context.Context, *PredictCongestionRequest) (*PredictCongestionResponse, error)
	RecommendRoute(context.Context, *RecommendRouteRequest) (*RecommendRouteResponse, error)
	PredictDemand(context.Context, *PredictDemandRequest) (*PredictDemandResponse, error)
	SuggestAssign(context.Context, *SuggestAssignRequest) (*SuggestAssignResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedAiServiceServer()
}

// UnimplementedAiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiServiceServer struct{}

func (UnimplementedAiServiceServer) PredictCongestion(context.Context, *PredictCongestionRequest) (*PredictCongestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PredictCongestion not implemented")
}
func (UnimplementedAiServiceServer) RecommendRoute(context.Context, *RecommendRouteRequest) (*RecommendRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecommendRoute not implemented")
}
func (UnimplementedAiServiceServer) PredictDemand(context.Context, *PredictDemandRequest) (*PredictDemandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PredictDemand not implemented")
}
func (UnimplementedAiServiceServer) SuggestAssign(context.Context, *SuggestAssignRequest) (*SuggestAssignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuggestAssign not implemented")
}
func (UnimplementedAiServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAiServiceServer) mustEmbedUnimplementedAiServiceServer() {}
func (UnimplementedAiServiceServer) testEmbeddedByValue()                   {}

// UnsafeAiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiServiceServer will
// result in compilation errors.
type UnsafeAiServiceServer interface {
	mustEmbedUnimplementedAiServiceServer()
}

func RegisterAiServiceServer(s grpc.ServiceRegistrar, srv AiServiceServer) {
	// If the following call pancis, it indicates UnimplementedAiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiService_ServiceDesc, srv)
}

func _AiService_PredictCongestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictCongestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).PredictCongestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_PredictCongestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).PredictCongestion(ctx, req.(*PredictCongestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_RecommendRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).RecommendRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_RecommendRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).RecommendRoute(ctx, req.(*RecommendRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_PredictDemand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictDemandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).PredictDemand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_PredictDemand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).PredictDemand(ctx, req.(*PredictDemandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_SuggestAssign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestAssignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).SuggestAssign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_SuggestAssign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).SuggestAssign(ctx, req.(*SuggestAssignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AiService_ServiceDesc is the grpc.ServiceDesc for AiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.v1.AiService",
	HandlerType: (*AiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PredictCongestion",
			Handler:    _AiService_PredictCongestion_Handler,
		},
		{
			MethodName: "RecommendRoute",
			Handler:    _AiService_RecommendRoute_Handler,
		},
		{
			MethodName: "PredictDemand",
			Handler:    _AiService_PredictDemand_Handler,
		},
		{
			MethodName: "SuggestAssign",
			Handler:    _AiService_SuggestAssign_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _AiService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ai/v1/ai.proto",
}
