// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.2
// source: proto/telemetry/v1/telemetry.proto

package telemetryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelemetryService_ReportLocation_FullMethodName     = "/telemetry.v1.TelemetryService/ReportLocation"
	TelemetryService_GetVehicleLocation_FullMethodName = "/telemetry.v1.TelemetryService/GetVehicleLocation"
	TelemetryService_GetNearbyVehicles_FullMethodName  = "/telemetry.v1.TelemetryService/GetNearbyVehicles"
)

// TelemetryServiceClient is the client API for TelemetryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelemetryServiceClient interface {
	ReportLocation(ctx context.Context, in *ReportLocationRequest, opts ...grpc.CallOption) (*ReportLocationResponse, error)
	GetVehicleLocation(ctx context.Context, in *GetVehicleLocationRequest, opts ...grpc.CallOption) (*GetVehicleLocationResponse, error)
	GetNearbyVehicles(ctx context.Context, in *GetNearbyVehiclesRequest, opts ...grpc.CallOption) (*GetNearbyVehiclesResponse, error)
}

type telemetryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryServiceClient(cc grpc.ClientConnInterface) TelemetryServiceClient {
	return &telemetryServiceClient{cc}
}

func (c *telemetryServiceClient) ReportLocation(ctx context.Context, in *ReportLocationRequest, opts ...grpc.CallOption) (*ReportLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportLocationResponse)
	err := c.cc.Invoke(ctx, TelemetryService_ReportLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) GetVehicleLocation(ctx context.Context, in *GetVehicleLocationRequest, opts ...grpc.CallOption) (*GetVehicleLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVehicleLocationResponse)
	err := c.cc.Invoke(ctx, TelemetryService_GetVehicleLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) GetNearbyVehicles(ctx context.Context, in *GetNearbyVehiclesRequest, opts ...grpc.CallOption) (*GetNearbyVehiclesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNearbyVehiclesResponse)
	err := c.cc.Invoke(ctx, TelemetryService_GetNearbyVehicles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelemetryServiceServer is the server API for TelemetryService service.
// All implementations must embed UnimplementedTelemetryServiceServer
// for forward compatibility.
type TelemetryServiceServer interface {
	ReportLocation(context.Context, *ReportLocationRequest) (*ReportLocationResponse, error)
	GetVehicleLocation(context.Context, *GetVehicleLocationRequest) (*GetVehicleLocationResponse, error)
	GetNearbyVehicles(context.Context, *GetNearbyVehiclesRequest) (*GetNearbyVehiclesResponse, error)
	mustEmbedUnimplementedTelemetryServiceServer()
}

// UnimplementedTelemetryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelemetryServiceServer struct{}

func (UnimplementedTelemetryServiceServer) ReportLocation(context.Context, *ReportLocationRequest) (*ReportLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportLocation not implemented")
}
func (UnimplementedTelemetryServiceServer) GetVehicleLocation(context.Context, *GetVehicleLocationRequest) (*GetVehicleLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVehicleLocation not implemented")
}
func (UnimplementedTelemetryServiceServer) GetNearbyVehicles(context.Context, *GetNearbyVehiclesRequest) (*GetNearbyVehiclesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNearbyVehicles not implemented")
}
func (UnimplementedTelemetryServiceServer) mustEmbedUnimplementedTelemetryServiceServer() {}
func (UnimplementedTelemetryServiceServer) testEmbeddedByValue()                          {}

// UnsafeTelemetryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryServiceServer will
// result in compilation errors.
type UnsafeTelemetryServiceServer interface {
	mustEmbedUnimplementedTelemetryServiceServer()
}

func RegisterTelemetryServiceServer(s grpc.ServiceRegistrar, srv TelemetryServiceServer) {
	// If the following call pancis, it indicates UnimplementedTelemetryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelemetryService_ServiceDesc, srv)
}

func _TelemetryService_ReportLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).ReportLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_ReportLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).ReportLocation(ctx, req.(*ReportLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_GetVehicleLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVehicleLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).GetVehicleLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_GetVehicleLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).GetVehicleLocation(ctx, req.(*GetVehicleLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_GetNearbyVehicles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNearbyVehiclesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).GetNearbyVehicles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_GetNearbyVehicles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).GetNearbyVehicles(ctx, req.(*GetNearbyVehiclesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TelemetryService_ServiceDesc is the grpc.ServiceDesc for TelemetryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.v1.TelemetryService",
	HandlerType: (*TelemetryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportLocation",
			Handler:    _TelemetryService_ReportLocation_Handler,
		},
		{
			MethodName: "GetVehicleLocation",
			Handler:    _TelemetryService_GetVehicleLocation_Handler,
		},
		{
			MethodName: "GetNearbyVehicles",
			Handler:    _TelemetryService_GetNearbyVehicles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/telemetry/v1/telemetry.proto",
}
