// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.2
// source: proto/report/v1/report.proto

package reportv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReportService_GetDashboardSummary_FullMethodName   = "/report.v1.ReportService/GetDashboardSummary"
	ReportService_GetDispatchReport_FullMethodName     = "/report.v1.ReportService/GetDispatchReport"
	ReportService_GetVehicleUtilization_FullMethodName = "/report.v1.ReportService/GetVehicleUtilization"
	ReportService_GetTransportVolume_FullMethodName    = "/report.v1.ReportService/GetTransportVolume"
	ReportService_GetAlarmTrend_FullMethodName         = "/report.v1.ReportService/GetAlarmTrend"
)

// ReportServiceClient is the client API for ReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReportServiceClient interface {
	GetDashboardSummary(ctx context.Context, in *DashboardSummaryRequest, opts ...grpc.CallOption) (*DashboardSummaryResponse, error)
	GetDispatchReport(ctx context.Context, in *DispatchReportRequest, opts ...grpc.CallOption) (*DispatchReportResponse, error)
	GetVehicleUtilization(ctx context.Context, in *VehicleUtilizationRequest, opts ...grpc.CallOption) (*VehicleUtilizationResponse, error)
	GetTransportVolume(ctx context.Context, in *TransportVolumeRequest, opts ...grpc.CallOption) (*TransportVolumeResponse, error)
	GetAlarmTrend(ctx context.Context, in *AlarmTrendRequest, opts ...grpc.CallOption) (*AlarmTrendResponse, error)
}

type reportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReportServiceClient(cc grpc.ClientConnInterface) ReportServiceClient {
	return &reportServiceClient{cc}
}

func (c *reportServiceClient) GetDashboardSummary(ctx context.Context, in *DashboardSummaryRequest, opts ...grpc.CallOption) (*DashboardSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DashboardSummaryResponse)
	err := c.cc.Invoke(ctx, ReportService_GetDashboardSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetDispatchReport(ctx context.Context, in *DispatchReportRequest, opts ...grpc.CallOption) (*DispatchReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchReportResponse)
	err := c.cc.Invoke(ctx, ReportService_GetDispatchReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetVehicleUtilization(ctx context.Context, in *VehicleUtilizationRequest, opts ...grpc.CallOption) (*VehicleUtilizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VehicleUtilizationResponse)
	err := c.cc.Invoke(ctx, ReportService_GetVehicleUtilization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetTransportVolume(ctx context.Context, in *TransportVolumeRequest, opts ...grpc.CallOption) (*TransportVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransportVolumeResponse)
	err := c.cc.Invoke(ctx, ReportService_GetTransportVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetAlarmTrend(ctx context.Context, in *AlarmTrendRequest, opts ...grpc.CallOption) (*AlarmTrendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlarmTrendResponse)
	err := c.cc.Invoke(ctx, ReportService_GetAlarmTrend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportServiceServer is the server API for ReportService service.
// All implementations must embed UnimplementedReportServiceServer
// for forward compatibility.
type ReportServiceServer interface {
	GetDashboardSummary(context.Context, *DashboardSummaryRequest) (*DashboardSummaryResponse, error)
	GetDispatchReport(context.Context, *DispatchReportRequest) (*DispatchReportResponse, error)
	GetVehicleUtilization(context.Context, *VehicleUtilizationRequest) (*VehicleUtilizationResponse, error)
	GetTransportVolume(context.Context, *TransportVolumeRequest) (*TransportVolumeResponse, error)
	GetAlarmTrend(context.Context, *AlarmTrendRequest) (*AlarmTrendResponse, error)
	mustEmbedUnimplementedReportServiceServer()
}

// UnimplementedReportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReportServiceServer struct{}

func (UnimplementedReportServiceServer) GetDashboardSummary(context.Context, *DashboardSummaryRequest) (*DashboardSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardSummary not implemented")
}
func (UnimplementedReportServiceServer) GetDispatchReport(context.Context, *DispatchReportRequest) (*DispatchReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDispatchReport not implemented")
}
func (UnimplementedReportServiceServer) GetVehicleUtilization(context.Context, *VehicleUtilizationRequest) (*VehicleUtilizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVehicleUtilization not implemented")
}
func (UnimplementedReportServiceServer) GetTransportVolume(context.Context, *TransportVolumeRequest) (*TransportVolumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransportVolume not implemented")
}
func (UnimplementedReportServiceServer) GetAlarmTrend(context.Context, *AlarmTrendRequest) (*AlarmTrendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlarmTrend not implemented")
}
func (UnimplementedReportServiceServer) mustEmbedUnimplementedReportServiceServer() {}
func (UnimplementedReportServiceServer) testEmbeddedByValue()                       {}

// UnsafeReportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportServiceServer will
// result in compilation errors.
type UnsafeReportServiceServer interface {
	mustEmbedUnimplementedReportServiceServer()
}

func RegisterReportServiceServer(s grpc.ServiceRegistrar, srv ReportServiceServer) {
	// If the following call pancis, it indicates UnimplementedReportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReportService_ServiceDesc, srv)
}

func _ReportService_GetDashboardSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DashboardSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetDashboardSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_GetDashboardSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetDashboardSummary(ctx, req.(*DashboardSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetDispatchReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetDispatchReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_GetDispatchReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetDispatchReport(ctx, req.(*DispatchReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetVehicleUtilization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VehicleUtilizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetVehicleUtilization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_GetVehicleUtilization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetVehicleUtilization(ctx, req.(*VehicleUtilizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetTransportVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransportVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetTransportVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_GetTransportVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetTransportVolume(ctx, req.(*TransportVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetAlarmTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlarmTrendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetAlarmTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_GetAlarmTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetAlarmTrend(ctx, req.(*AlarmTrendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReportService_ServiceDesc is the grpc.ServiceDesc for ReportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "report.v1.ReportService",
	HandlerType: (*ReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDashboardSummary",
			Handler:    _ReportService_GetDashboardSummary_Handler,
		},
		{
			MethodName: "GetDispatchReport",
			Handler:    _ReportService_GetDispatchReport_Handler,
		},
		{
			MethodName: "GetVehicleUtilization",
			Handler:    _ReportService_GetVehicleUtilization_Handler,
		},
		{
			MethodName: "GetTransportVolume",
			Handler:    _ReportService_GetTransportVolume_Handler,
		},
		{
			MethodName: "GetAlarmTrend",
			Handler:    _ReportService_GetAlarmTrend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/report/v1/report.proto",
}
